apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: simple-social-db
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: simple-social-db-creds
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: "rds!db-fecb6266-912d-48a6-b04c-52b36f1ae436-qC8GpL"
        property: password